const MEINE_REISEN = [
  { "Platz": 1, "Land": "Deutschland", "Wohnorte": 4, "Übernachtungen": 45, "Unterkünfte": 20, "FluegeAnkunft": 18, "Tagestrips": 0, "Joggen": 3, "km_gejoggt": 754 },
  { "Platz": 2, "Land": "Schweiz", "Wohnorte": 0, "Übernachtungen": 15, "Unterkünfte": 8, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 5, "km_gejoggt": 40 },
  { "Platz": 3, "Land": "Griechenland", "Wohnorte": 0, "Übernachtungen": 7, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 5 },
  { "Platz": 4, "Land": "Mauritius", "Wohnorte": 0, "Übernachtungen": 6, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 2, "km_gejoggt": 31 },
  { "Platz": 5, "Land": "USA", "Wohnorte": 0, "Übernachtungen": 6, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 7 },
  { "Platz": 6, "Land": "Zypern", "Wohnorte": 0, "Übernachtungen": 5, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 4, "km_gejoggt": 35 },
  { "Platz": 7, "Land": "Türkei", "Wohnorte": 0, "Übernachtungen": 5, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 2, "km_gejoggt": 11 },
  { "Platz": 8, "Land": "Dänemark", "Wohnorte": 0, "Übernachtungen": 4, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 3, "km_gejoggt": 19 },
  { "Platz": 9, "Land": "Schweden", "Wohnorte": 0, "Übernachtungen": 4, "Unterkünfte": 1, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 5 },
  { "Platz": 10, "Land": "Litauen", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 2, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 3, "km_gejoggt": 26 },
  { "Platz": 11, "Land": "Lettland", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 12, "Land": "Österreich", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 13, "Land": "Belgien", "Wohnorte": 0, "Übernachtungen": 4, "Unterkünfte": 3, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 14, "Land": "Internationale Gewässer", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 15, "Land": "Spanien", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 4, "km_gejoggt": 27 },
  { "Platz": 16, "Land": "Luxemburg", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 4, "km_gejoggt": 21 },
  { "Platz": 17, "Land": "Niederlande", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 2, "km_gejoggt": 10 },
  { "Platz": 18, "Land": "Norwegen", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 10 },
  { "Platz": 19, "Land": "Frankreich", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 20, "Land": "Italien", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 21, "Land": "England", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 22, "Land": "Vatikan", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 23, "Land": "Vereinigte Arabische Emirate", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 24, "Land": "Malta", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 25, "Land": "Gibraltar", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 26, "Land": "Marokko", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 27, "Land": "Ungarn", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 28, "Land": "Portugal", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "Platz": 29, "Land": "Slowakei", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 }
];
