const MEINE_REISEN = [
  { "id": "DE", "Land": "Deutschland", "Wohnorte": 4, "Übernachtungen": 45, "Unterkünfte": 20, "FluegeAnkunft": 18, "Tagestrips": 0, "Joggen": 3, "km_gejoggt": 754 },
  { "id": "CH", "Land": "Schweiz", "Wohnorte": 0, "Übernachtungen": 15, "Unterkünfte": 8, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 5, "km_gejoggt": 40 },
  { "id": "GR", "Land": "Griechenland", "Wohnorte": 0, "Übernachtungen": 7, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 5 },
  { "id": "MU", "Land": "Mauritius", "Wohnorte": 0, "Übernachtungen": 6, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 2, "km_gejoggt": 31 },
  { "id": "US", "Land": "USA", "Wohnorte": 0, "Übernachtungen": 6, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 7 },
  { "id": "CY", "Land": "Zypern", "Wohnorte": 0, "Übernachtungen": 5, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 4, "km_gejoggt": 35 },
  { "id": "TR", "Land": "Türkei", "Wohnorte": 0, "Übernachtungen": 5, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 2, "km_gejoggt": 11 },
  { "id": "BE", "Land": "Belgien", "Wohnorte": 0, "Übernachtungen": 4, "Unterkünfte": 3, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "DK", "Land": "Dänemark", "Wohnorte": 0, "Übernachtungen": 4, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 3, "km_gejoggt": 19 },
  { "id": "SE", "Land": "Schweden", "Wohnorte": 0, "Übernachtungen": 4, "Unterkünfte": 1, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 5 },
  { "id": "LT", "Land": "Litauen", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 2, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 3, "km_gejoggt": 26 },
  { "id": "LV", "Land": "Lettland", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "AT", "Land": "Österreich", "Wohnorte": 0, "Übernachtungen": 3, "Unterkünfte": 2, "FluegeAnkunft": 1, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "ES", "Land": "Spanien", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 4, "km_gejoggt": 27 },
  { "id": "LU", "Land": "Luxemburg", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 4, "km_gejoggt": 21 },
  { "id": "NL", "Land": "Niederlande", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 2, "km_gejoggt": 10 },
  { "id": "NO", "Land": "Norwegen", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 1, "km_gejoggt": 10 },
  { "id": "FR", "Land": "Frankreich", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "IT", "Land": "Italien", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "GB", "Land": "England", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "VA", "Land": "Vatikan", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "AE", "Land": "Vereinigte Arabische Emirate", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "MT", "Land": "Malta", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "GI", "Land": "Gibraltar", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "MA", "Land": "Marokko", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "HU", "Land": "Ungarn", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "PT", "Land": "Portugal", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 },
  { "id": "SK", "Land": "Slowakei", "Wohnorte": 0, "Übernachtungen": 1, "Unterkünfte": 1, "FluegeAnkunft": 0, "Tagestrips": 0, "Joggen": 0, "km_gejoggt": 0 }
];
