const MEINE_REISEN = [
  { 
    "id": "DE", 
    "Land": "Deutschland", 
    "name_en": "Germany", 
    "Wohnorte": 4, 
    "Übernachtungen": 45, 
    "Unterkünfte": 20, 
    "FluegeAnkunft": 18, 
    "Tagestrips": 0, 
    "Joggen": 3, 
    "km_gejoggt": 754 
  },
  { 
    "id": "CH", 
    "Land": "Schweiz", 
    "name_en": "Switzerland", 
    "Wohnorte": 0, 
    "Übernachtungen": 15, 
    "Unterkünfte": 8, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 5, 
    "km_gejoggt": 40 
  },
  { 
    "id": "GR", 
    "Land": "Griechenland", 
    "name_en": "Greece", 
    "Wohnorte": 0, 
    "Übernachtungen": 7, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 1, 
    "km_gejoggt": 5 
  },
  { 
    "id": "MU", 
    "Land": "Mauritius", 
    "name_en": "Mauritius", 
    "Wohnorte": 0, 
    "Übernachtungen": 6, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 2, 
    "km_gejoggt": 31 
  },
  { 
    "id": "US", 
    "Land": "USA", 
    "name_en": "United States of America", 
    "Wohnorte": 0, 
    "Übernachtungen": 6, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 1, 
    "km_gejoggt": 7 
  },
  { 
    "id": "CY", 
    "Land": "Zypern", 
    "name_en": "Cyprus", 
    "Wohnorte": 0, 
    "Übernachtungen": 5, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 4, 
    "km_gejoggt": 35 
  },
  { 
    "id": "TR", 
    "Land": "Türkei", 
    "name_en": "Turkey", 
    "Wohnorte": 0, 
    "Übernachtungen": 5, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 2, 
    "km_gejoggt": 11 
  },
  { 
    "id": "BE", 
    "Land": "Belgien", 
    "name_en": "Belgium", 
    "Wohnorte": 0, 
    "Übernachtungen": 4, 
    "Unterkünfte": 3, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "DK", 
    "Land": "Dänemark", 
    "name_en": "Denmark", 
    "Wohnorte": 0, 
    "Übernachtungen": 4, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 3, 
    "km_gejoggt": 19 
  },
  { 
    "id": "SE", 
    "Land": "Schweden", 
    "name_en": "Sweden", 
    "Wohnorte": 0, 
    "Übernachtungen": 4, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 1, 
    "km_gejoggt": 5 
  },
  { 
    "id": "LT", 
    "Land": "Litauen", 
    "name_en": "Lithuania", 
    "Wohnorte": 0, 
    "Übernachtungen": 3, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 3, 
    "km_gejoggt": 26 
  },
  { 
    "id": "LV", 
    "Land": "Lettland", 
    "name_en": "Latvia", 
    "Wohnorte": 0, 
    "Übernachtungen": 3, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "AT", 
    "Land": "Österreich", 
    "name_en": "Austria", 
    "Wohnorte": 0, 
    "Übernachtungen": 3, 
    "Unterkünfte": 2, 
    "FluegeAnkunft": 1, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "ES", 
    "Land": "Spanien", 
    "name_en": "Spain", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 4, 
    "km_gejoggt": 27 
  },
  { 
    "id": "LU", 
    "Land": "Luxemburg", 
    "name_en": "Luxembourg", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 4, 
    "km_gejoggt": 21 
  },
  { 
    "id": "NL", 
    "Land": "Niederlande", 
    "name_en": "Netherlands", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 2, 
    "km_gejoggt": 10 
  },
  { 
    "id": "NO", 
    "Land": "Norwegen", 
    "name_en": "Norway", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 1, 
    "km_gejoggt": 10 
  },
  { 
    "id": "FR", 
    "Land": "Frankreich", 
    "name_en": "France", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "IT", 
    "Land": "Italien", 
    "name_en": "Italy", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "GB", 
    "Land": "England", 
    "name_en": "United Kingdom", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "VA", 
    "Land": "Vatikan", 
    "name_en": "Vatican City", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "AE", 
    "Land": "Vereinigte Arabische Emirate", 
    "name_en": "United Arab Emirates", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "MT", 
    "Land": "Malta", 
    "name_en": "Malta", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "GI", 
    "Land": "Gibraltar", 
    "name_en": "Gibraltar", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "MA", 
    "Land": "Marokko", 
    "name_en": "Morocco", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "HU", 
    "Land": "Ungarn", 
    "name_en": "Hungary", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "PT", 
    "Land": "Portugal", 
    "name_en": "Portugal", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  },
  { 
    "id": "SK", 
    "Land": "Slowakei", 
    "name_en": "Slovakia", 
    "Wohnorte": 0, 
    "Übernachtungen": 1, 
    "Unterkünfte": 1, 
    "FluegeAnkunft": 0, 
    "Tagestrips": 0, 
    "Joggen": 0, 
    "km_gejoggt": 0 
  }
];
